# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pplx < Formula
  desc ""
  homepage "https://github.com/japelsin/pplx"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/japelsin/pplx/releases/download/v0.3.1/pplx_Darwin_arm64.tar.gz"
      sha256 "8099aa914e671a261cde134fa6344a33e069dd8266d8dcf2168875009be36159"

      def install
        bin.install "pplx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/japelsin/pplx/releases/download/v0.3.1/pplx_Darwin_x86_64.tar.gz"
      sha256 "45de6a3087d1f96c9a998393f2134b700d63e846c45a3225563fefe6d5cc4748"

      def install
        bin.install "pplx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/japelsin/pplx/releases/download/v0.3.1/pplx_Linux_arm64.tar.gz"
      sha256 "de1259f128c6e4870130909171c6dec8623b64fce93321eed582354ee26870ef"

      def install
        bin.install "pplx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/japelsin/pplx/releases/download/v0.3.1/pplx_Linux_x86_64.tar.gz"
      sha256 "46333a8133dd7305aa293deda47d6fe56836bcc7e8642bc08f099f86e0dc8aee"

      def install
        bin.install "pplx"
      end
    end
  end
end
